// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Roupas",
                            Description = "Camiseta do curso de ASP.NET Core Web API",
                            ImageUrl = "https://raw.githubusercontent.com/GeekShopping/GeekShopping/master/Images/Products/camiseta.png",
                            Name = "Camiseta",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Acessórios",
                            Description = "Caneca do curso de ASP.NET Core Web API",
                            ImageUrl = "https://raw.githubusercontent.com/GeekShopping/GeekShopping/master/Images/Products/caneca.png",
                            Name = "Caneca",
                            Price = 29.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Roupas",
                            Description = "Moleton do curso de ASP.NET Core Web API",
                            ImageUrl = "https://raw.githubusercontent.com/GeekShopping/GeekShopping/master/Images/Products/moletom.png",
                            Name = "Moleton",
                            Price = 119.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Acessórios",
                            Description = "Mousepad do curso de ASP.NET Core Web API",
                            ImageUrl = "https://raw.githubusercontent.com/GeekShopping/GeekShopping/master/Images/Products/mousepad.png",
                            Name = "Mousepad",
                            Price = 19.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
